services:
    # PHP-FPM Service
    it-fpm:
        build:
            args:
                user: sammy
                uid: 1000
            context: .
            dockerfile: dockerfile.fpm
        container_name: it-fpm
        restart: unless-stopped
        tty: true
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            APP_URL: ${APP_URL}
            PHP_IDE_CONFIG: "serverName=Docker"
            FORCE_SSL: "false"
            XDEBUG_CONFIG: "remote_host=host.docker.network remote_enable=1"
            APP_ENV: ${APP_ENV}
        working_dir: /var/www/html/
        extra_hosts:
            - docker.for.win.localhost:host-gateway
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/html/:rw
            - ./storage:/var/www/html/storage:rw
            - ./docker/php.ini:/usr/local/etc/php/php.ini:cached
        networks:
            - network

    # Nginx Service
    it-nginx:
        image: nginx:alpine
        container_name: it-nginx
        restart: unless-stopped
        depends_on:
            - it-fpm
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./storage:/var/www/html/storage:rw
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - network

    # MySQL Service
    it-db:
        image: mysql:5.6
        container_name: it-db
        restart: always
        tty: true
        command: --default-authentication-plugin=mysql_native_password
        environment:
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "127.0.0.1:3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql/
        networks:
            - network

#Docker Networks
networks:
    network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.168.219.0/28
